nowarp/misti

- CHANGELOG.md
- src/driver.ts
- src/main.ts
> feat(driver): Add `--dump-config`

- CHANGELOG.md
- configSchema.json
- examples/implicit-init/test/project/mistiConfig.json
- src/detectors/builtin/neverAccessedVariables.ts
- src/detectors/builtin/readOnlyVariables.ts
- src/detectors/detector.ts
- src/internals/config.ts
- test/good/never-accessed-9.cfg.dot
- test/good/never-accessed-9.cfg.json
- test/good/never-accessed-9.tact
- test/good/readonly-5.cfg.dot
- test/good/readonly-5.cfg.json
- test/good/readonly-5.tact
> Naming convention to skip unused identifiers

- CHANGELOG.md
- src/detectors/builtin/constantAddress.ts
- src/detectors/builtin/divideBeforeMultiply.ts
- src/detectors/builtin/neverAccessedVariables.ts
- src/detectors/builtin/readOnlyVariables.ts
- src/detectors/builtin/unboundLoops.ts
- src/detectors/builtin/zeroAddress.ts
- src/detectors/detector.ts
- src/driver.ts
- src/internals/config.ts
- src/internals/context.ts
- src/main.ts
- test/builtinDetectors.spec.ts
- test/config.spec.ts
- test/good/constant-address-1.cfg.dot
- test/good/constant-address-1.cfg.json
- test/good/constant-address-1.expected.out
- test/good/constant-address-1.tact
- test/good/zero-address.expected.out
> `ConstantAddress` detector + required refactorings

- .github/workflows/ci.yml
- .lycheeignore
- CONTRIBUTING.md
- README.md
> Fix broken links

- CHANGELOG.md
- benchmarks/detectors.ts
- test/good/sample-jetton.cfg.dot
- test/good/sample-jetton.cfg.json
- test/good/sample-jetton.expected.out
- test/good/sample-jetton.tact
> Add benchmarks

- CHANGELOG.md
- src/detectors/builtin/divideBeforeMultiply.ts
- src/detectors/builtin/neverAccessedVariables.ts
- src/detectors/builtin/readOnlyVariables.ts
- src/detectors/builtin/stringReceiversOverlap.ts
- src/detectors/builtin/unboundLoops.ts
- src/detectors/detector.ts
- src/internals/ir/astStore.ts
- src/internals/ir/builders/tactIRBuilder.ts
- src/internals/ir/cfg.ts
- src/internals/ir/ir.ts
- src/internals/irDump.ts
- test/good/string-receivers-overlap-1.cfg.dot
- test/good/string-receivers-overlap-1.cfg.json
- test/good/string-receivers-overlap-1.expected.out
- test/good/string-receivers-overlap-1.tact
> New detector: `StringReceiversOverlap`

- .github/workflows/ci.yml
- CONTRIBUTING.md
- HACKING.md
Based on fix Developing Misti page https://github.com/nowarp/nowarp.github.io/pull/17
Now information has been move to documentation.
> Remove unneeded files 

- src/detectors/builtin/sendInLoop.ts
> fix: add docstrings

- src/cli/driver.ts
- src/internals/ir/builders/astStore.ts
- src/internals/ir/builders/index.ts
- src/internals/ir/builders/ir.ts
- src/internals/ir/builders/tactConfig.ts
- src/internals/ir/builders/tactStdlib.ts
- src/internals/ir/index.ts
- src/internals/util.ts
> Refactor `ir/builders`

- CHANGELOG.md
- package.json
- src/cli/driver.ts
- yarn.lock
> Driver: Accept directory as input

- CHANGELOG.md
- src/cli/driver.ts
- src/detectors/detector.ts
- src/index.ts
- src/internals/annotation.ts
- src/internals/tact/util.ts
- src/internals/warnings.ts
- test/detectors/AsmIsUsed.tact
- test/detectors/FieldDoubleInit.expected.out
- test/detectors/FieldDoubleInit.tact
> Support suppression annotations

- .github/workflows/ci.yml
- CHANGELOG.md
> CI: Fix Souffle installation

- CHANGELOG.md
- sample.tact
- src/cli/driver.ts
- src/cli/result.ts
- src/internals/context.ts
- src/internals/logger.ts
- test/cli.spec.ts
> Logger: Save JSON output

- CHANGELOG.md
- src/internals/ir/callGraph.ts
- test/all/syntax.expected.callgraph.dot
- test/all/syntax.expected.callgraph.json
- test/all/syntax.expected.callgraph.mmd
- test/all/syntax.expected.cfg.dot
- test/all/syntax.expected.cfg.json
- test/all/syntax.expected.cfg.mmd
- test/all/syntax.expected.out
- test/all/syntax.tact
> Callgraph: Add asm functions

- CHANGELOG.md
- src/detectors/builtin/ensurePrgSeed.ts
- src/internals/ir/callGraph.ts
- src/internals/tact/stdlib.ts
- src/internals/tact/util.ts
- test/all/syntax.expected.callgraph.dot
- test/all/syntax.expected.callgraph.json
- test/all/syntax.expected.callgraph.mmd
- test/all/syntax.expected.cfg.dot
- test/all/syntax.expected.cfg.json
- test/all/syntax.expected.cfg.mmd
- test/all/syntax.expected.out
- test/all/syntax.tact
> fix(callgraph): Incorrect processing of `StateWrite` for cells

- CHANGELOG.md
- src/internals/ir/callGraph.ts
- src/tools/dumpCallgraph.ts
- test/all/sample-jetton.expected.callgraph.dot
- test/all/sample-jetton.expected.callgraph.mmd
- test/all/syntax.expected.callgraph.dot
- test/all/syntax.expected.callgraph.json
- test/all/syntax.expected.callgraph.mmd
- test/all/syntax.expected.cfg.dot
- test/all/syntax.expected.cfg.json
- test/all/syntax.expected.cfg.mmd
- test/all/syntax.expected.out
- test/all/syntax.tact
> Callgraph: Save field names used in `Effect.State{Read,Write}`

- .github/workflows/ci.yml
See: https://github.com/tact-lang/tact/pull/1899
> feat(ci): Cancel previous CI run if a new commit pushed to PR

- CHANGELOG.md
- src/tools/dumpCallgraph.ts
- test/all/sample-jetton.expected.callgraph.dot
- test/all/sample-jetton.expected.callgraph.mmd
- test/all/syntax.expected.callgraph.dot
- test/all/syntax.expected.callgraph.mmd
> Callgraph: Highlight stdlib function calls in dump

- CHANGELOG.md
- src/detectors/builtin/sendInLoop.ts
- src/internals/ir/builders/callgraph.ts
- src/internals/ir/builders/index.ts
- src/internals/ir/builders/ir.ts
- src/internals/ir/callGraph.ts
> Callgraph: Separate building logic

- CHANGELOG.md
- examples/implicit-init/implicitInit.ts
- src/internals/ir/builders/ir.ts
- src/internals/ir/ir.ts
- src/tools/dumpCfg.ts
- test/all/sample-jetton.expected.cfg.dot
- test/all/sample-jetton.expected.cfg.json
- test/all/sample-jetton.expected.cfg.mmd
- test/all/syntax.expected.cfg.dot
- test/all/syntax.expected.cfg.json
- test/all/syntax.expected.cfg.mmd
> IR: Support traits

- .github/workflows/ci.yml
- .github/workflows/deploy-docs.yml
- CHANGELOG.md
- package.json
> Add support version node v23

- CHANGELOG.md
- src/cli/driver.ts
- src/internals/logger.ts
> Logger: Add detector contexts

- CHANGELOG.md
- package.json
- src/internals/tact/imports.ts
- test/all/sample-jetton.expected.cfg.dot
- test/all/sample-jetton.expected.cfg.json
- test/all/sample-jetton.expected.cfg.mmd
- test/all/syntax.expected.cfg.dot
- test/all/syntax.expected.cfg.json
- test/all/syntax.expected.cfg.mmd
- yarn.lock
> Support Tact 1.6.2 with new imports structure

- CHANGELOG.md
- README.md
- src/detectors/builtin/preferDeploy.ts
- src/detectors/detector.ts
- test/all/sample-jetton.expected.out
- test/detectors/PreferDeploy.expected.out
- test/detectors/PreferDeploy.tact
> Add `PreferDeploy` detector

- CHANGELOG.md
- src/cli/driver.ts
- src/internals/tact/stdlib.ts
- src/internals/util.ts
> Fix and improve browser support 

- CHANGELOG.md
- README.md
- src/detectors/builtin/duplicatedImport.ts
- src/detectors/detector.ts
- src/internals/ir/builders/imports.ts
- src/internals/ir/imports.ts
- src/tools/dumpImports.ts
- test/all/imports-4/main.tact
- test/all/sample-jetton.expected.json
- test/all/syntax.expected.json
- test/detectors/DuplicatedImport.expected.out
- test/detectors/DuplicatedImport.tact
> `DuplicatedImport` detector

- CHANGELOG.md
- README.md
- examples/README.md
- examples/contract-summary/contractSummary.ts
- examples/contract-summary/test.tact
- src/cli/driver.ts
- src/cli/options.ts
- src/cli/types.ts
- src/internals/config.ts
- src/tools/tool.ts
> feat(tools): Support dynamic loading of tools
